add_subdirectory(core)
add_subdirectory(math)
add_subdirectory(camera)
add_subdirectory(jobs)
add_subdirectory(platform)
add_subdirectory(rhi)
add_subdirectory(rhi/d3d12)
add_subdirectory(shader)
add_subdirectory(shader/d3d)
add_subdirectory(debug_render)
add_subdirectory(world)
add_subdirectory(terrain)
add_subdirectory(terrain_hydrology)
add_subdirectory(terrain_erosion)
add_subdirectory(terrain_cache)
add_subdirectory(terrain_view)
add_subdirectory(terrain_stream)
add_subdirectory(terrain_render)
