#include <orbit/world_model/CelestialSchemas.hpp>

#include <string>
#include <utility>

namespace orbit::world_model
{
namespace
{
schema::PropertySchema EnabledProperty()
{
    return {
        .id = kCapabilityEnabled,
        .name = "Enabled",
        .kind = schema::PropertyKind::Boolean,
        .defaultValue = true
    };
}

schema::PropertySchema ModelProperty(std::string defaultModel)
{
    return {
        .id = kCapabilityModel,
        .name = "Model",
        .kind = schema::PropertyKind::String,
        .defaultValue = std::move(defaultModel),
        .advanced = true
    };
}

schema::PropertySchema SourceObjectProperty()
{
    return {
        .id = kCapabilitySourceObject,
        .name = "Source Object",
        .kind = schema::PropertyKind::ObjectReference,
        .defaultValue = schema::ObjectReferenceValue{},
        .advanced = true
    };
}

void RegisterCapability(
    schema::SchemaRegistry& schemas,
    const schema::TypeId id,
    std::string displayName,
    std::string defaultModel,
    const bool sourceObject = false)
{
    schema::TypeSchema type{
        .id = id,
        .displayName = std::move(displayName),
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty(std::move(defaultModel))
        }
    };

    if (sourceObject)
    {
        type.properties.push_back(SourceObjectProperty());
    }

    schemas.RegisterType(std::move(type));
}
} // namespace

void RegisterCelestialCapabilitySchemas(
    schema::SchemaRegistry& schemas)
{
    schemas.RegisterType({
        .id = kEphemerisAssetType,
        .displayName = "Ephemeris Asset",
        .category = "Celestial/Imported Data",
        .properties = {
            {.id = kEphemerisSourceLabel,
             .name = "Source Label",
             .kind = schema::PropertyKind::String,
             .defaultValue = std::string{}}
        }
    });

    schemas.RegisterType({
        .id = kEphemerisSampleType,
        .displayName = "Ephemeris Sample",
        .category = "Celestial/Imported Data",
        .properties = {
            {.id = kEphemerisSampleTimeMicroseconds,
             .name = "Time",
             .kind = schema::PropertyKind::Integer,
             .unit = "us",
             .defaultValue = i64{0}},
            {.id = kEphemerisSamplePositionMeters,
             .name = "Position",
             .kind = schema::PropertyKind::Vector3,
             .unit = "m",
             .defaultValue = math::Double3{}},
            {.id = kEphemerisSampleVelocityMetersPerSecond,
             .name = "Velocity",
             .kind = schema::PropertyKind::Vector3,
             .unit = "m/s",
             .defaultValue = math::Double3{}}
        }
    });

    RegisterCapability(
        schemas, kReferenceShapeCapabilityType,
        "Reference Shape", "Sphere");
    RegisterCapability(
        schemas, kMassPropertiesCapabilityType,
        "Mass Properties", "Explicit");
    schemas.RegisterType({
        .id = kOrbitCapabilityType,
        .displayName = "Orbit / Ephemeris",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Fixed"),
            SourceObjectProperty(),
            {.id = kOrbitSemiMajorAxisMeters,
             .name = "Semi-major Axis Magnitude",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1.0,
             .range = {.minimum = 0.000001}},
            {.id = kOrbitPeriapsisDistanceMeters,
             .name = "Periapsis Distance",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1.0,
             .range = {.minimum = 0.000001}},
            {.id = kOrbitEccentricity,
             .name = "Eccentricity",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.0,
             .range = {.minimum = 0.0}},
            {.id = kOrbitInclinationDegrees,
             .name = "Inclination",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0},
            {.id = kOrbitAscendingNodeDegrees,
             .name = "Longitude of Ascending Node",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0},
            {.id = kOrbitArgumentPeriapsisDegrees,
             .name = "Argument of Periapsis",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0},
            {.id = kOrbitMeanAnomalyEpochDegrees,
             .name = "Mean Anomaly At Epoch",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0},
            {.id = kOrbitBarkerParameterEpoch,
             .name = "Barker Parameter At Epoch",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.0,
             .advanced = true},
            {.id = kOrbitGravitationalParameter,
             .name = "Gravitational Parameter",
             .kind = schema::PropertyKind::Float,
             .unit = "m3/s2",
             .defaultValue = 1.0,
             .range = {.minimum = 0.000001}},
            {.id = kOrbitEpochMicroseconds,
             .name = "Orbit Epoch",
             .kind = schema::PropertyKind::Integer,
             .unit = "us",
             .defaultValue = i64{0},
             .advanced = true},
            {.id = kOrbitDynamicPromotionEnabled,
             .name = "Dynamic N-Body Promotion",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = false,
             .advanced = true},
            {.id = kOrbitDynamicStepSeconds,
             .name = "N-Body Step",
             .kind = schema::PropertyKind::Float,
             .unit = "s",
             .defaultValue = 60.0,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kOrbitDynamicSofteningMeters,
             .name = "N-Body Softening",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 0.0,
             .range = {.minimum = 0.0},
             .advanced = true}
        }
    });
    schemas.RegisterType({
        .id = kGravityCapabilityType,
        .displayName = "Gravity",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Point Mass"),
            {.id = kGravityDeriveMuFromMass,
             .name = "Derive Mu From Body Mass",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true},
            {.id = kGravityMuM3PerS2,
             .name = "Gravitational Parameter",
             .kind = schema::PropertyKind::Float,
             .unit = "m3/s2",
             .defaultValue = 1.0,
             .range = {.minimum = 0.0}},
            {.id = kGravitySofteningMeters,
             .name = "Softening",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 0.0,
             .range = {.minimum = 0.0},
             .advanced = true}
        }
    });

    schemas.RegisterType({
        .id = kRotationCapabilityType,
        .displayName = "Rotation / Orientation",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Uniform Spin"),
            SourceObjectProperty(),
            {.id = kRotationAxis,
             .name = "Pole Axis",
             .kind = schema::PropertyKind::Vector3,
             .defaultValue = math::Double3{0.0, 0.0, 1.0}},
            {.id = kRotationPeriodSeconds,
             .name = "Rotation Period",
             .kind = schema::PropertyKind::Float,
             .unit = "s",
             .defaultValue = 86'400.0,
             .range = {.minimum = 0.000001}},
            {.id = kRotationPhaseDegrees,
             .name = "Phase At Epoch",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0},
            {.id = kRotationEpochMicroseconds,
             .name = "Rotation Epoch",
             .kind = schema::PropertyKind::Integer,
             .unit = "us",
             .defaultValue = i64{0},
             .advanced = true},
            {.id = kRotationSynchronousPhaseOffsetDegrees,
             .name = "Synchronous Phase Offset",
             .kind = schema::PropertyKind::Float,
             .unit = "deg",
             .defaultValue = 0.0,
             .advanced = true}
        }
    });
    RegisterCapability(
        schemas, kSurfaceCapabilityType,
        "Surface", "Terrain Authority", true);
    schemas.RegisterType({
        .id = kAtmosphereCapabilityType,
        .displayName = "Atmosphere",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Physical Scattering"),
            {.id = kAtmosphereAuthoringMode,
             .name = "Authoring Mode",
             .kind = schema::PropertyKind::String,
             .defaultValue = std::string{"Derived Composition"}},
            {.id = kAtmospherePreset,
             .name = "Preset",
             .kind = schema::PropertyKind::String,
             .defaultValue = std::string{"Earth-like"}},
            {.id = kAtmosphereSurfacePressurePascals,
             .name = "Surface Pressure",
             .kind = schema::PropertyKind::Float,
             .unit = "Pa",
             .defaultValue = 101325.0,
             .range = {.minimum = 0.000001}},
            {.id = kAtmosphereSurfaceTemperatureKelvin,
             .name = "Surface Temperature",
             .kind = schema::PropertyKind::Float,
             .unit = "K",
             .defaultValue = 288.15,
             .range = {.minimum = 0.000001}},
            {.id = kAtmosphereSurfaceGravityMetersPerSecondSquared,
             .name = "Surface Gravity",
             .kind = schema::PropertyKind::Float,
             .unit = "m/s2",
             .defaultValue = 9.80665,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereNitrogenFraction,
             .name = "Nitrogen Fraction",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.78084,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kAtmosphereOxygenFraction,
             .name = "Oxygen Fraction",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.20946,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kAtmosphereArgonFraction,
             .name = "Argon Fraction",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.00934,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kAtmosphereCarbonDioxideFraction,
             .name = "Carbon Dioxide Fraction",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.00036,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kAtmosphereAerosolOpticalDepth550,
             .name = "Aerosol Optical Depth 550 nm",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.005328,
             .range = {.minimum = 0.0},
             .advanced = true},
            {.id = kAtmosphereAerosolSingleScatteringAlbedo,
             .name = "Aerosol Single Scattering Albedo",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.90,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kAtmosphereAerosolAngstromExponent,
             .name = "Aerosol Angstrom Exponent",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.3,
             .range = {.minimum = 0.0},
             .advanced = true},
            {.id = kAtmosphereAerosolScaleHeightMeters,
             .name = "Aerosol Scale Height",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1200.0,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereAbsorberScale,
             .name = "Absorber Column Scale",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.0,
             .range = {.minimum = 0.0},
             .advanced = true},
            {.id = kAtmosphereTopRadiusMeters,
             .name = "Top Radius",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 6.471e6,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereRayleighScatteringPerMeter,
             .name = "Rayleigh Scattering",
             .kind = schema::PropertyKind::Vector3,
             .unit = "1/m",
             .defaultValue = math::Double3{
                 5.802e-6, 13.558e-6, 33.1e-6},
             .advanced = true},
            {.id = kAtmosphereRayleighScaleHeightMeters,
             .name = "Rayleigh Scale Height",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 8000.0,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereMieScatteringPerMeter,
             .name = "Mie Scattering",
             .kind = schema::PropertyKind::Vector3,
             .unit = "1/m",
             .defaultValue = math::Double3{
                 3.996e-6, 3.996e-6, 3.996e-6},
             .advanced = true},
            {.id = kAtmosphereMieExtinctionPerMeter,
             .name = "Mie Extinction",
             .kind = schema::PropertyKind::Vector3,
             .unit = "1/m",
             .defaultValue = math::Double3{
                 4.44e-6, 4.44e-6, 4.44e-6},
             .advanced = true},
            {.id = kAtmosphereMieScaleHeightMeters,
             .name = "Mie Scale Height",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1200.0,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereMieAnisotropy,
             .name = "Mie Anisotropy",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.8,
             .range = {.minimum = -0.999, .maximum = 0.999},
             .advanced = true},
            {.id = kAtmosphereAbsorptionExtinctionPerMeter,
             .name = "Absorption Extinction",
             .kind = schema::PropertyKind::Vector3,
             .unit = "1/m",
             .defaultValue = math::Double3{
                 0.650e-6, 1.881e-6, 0.085e-6},
             .advanced = true},
            {.id = kAtmosphereAbsorptionCenterHeightMeters,
             .name = "Absorption Layer Center",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 25000.0,
             .range = {.minimum = 0.0},
             .advanced = true},
            {.id = kAtmosphereAbsorptionHalfWidthMeters,
             .name = "Absorption Layer Half Width",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 15000.0,
             .range = {.minimum = 0.000001},
             .advanced = true},
            {.id = kAtmosphereGroundAlbedo,
             .name = "Ground Albedo",
             .kind = schema::PropertyKind::Vector3,
             .defaultValue = math::Double3{
                 0.10, 0.10, 0.10},
             .advanced = true}
        }
    });
    schemas.RegisterType({
        .id = kOceanCapabilityType,
        .displayName = "Ocean",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Surface Authority"),
            SourceObjectProperty(),
            {.id = kOceanRefractiveIndex,
             .name = "Refractive Index",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.333,
             .range = {.minimum = 1.0, .maximum = 2.5}},
            {.id = kOceanOrbitalRoughness,
             .name = "Orbital Roughness",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.12,
             .range = {.minimum = 0.01, .maximum = 1.0}},
            {.id = kOceanAbsorptionPerMeter,
             .name = "Absorption",
             .kind = schema::PropertyKind::Vector3,
             .unit = "1/m",
             .defaultValue = math::Double3{
                 0.18, 0.055, 0.025},
             .advanced = true},
            {.id = kOceanDeepWaterColor,
             .name = "Deep Water Color",
             .kind = schema::PropertyKind::Vector3,
             .defaultValue = math::Double3{
                 0.008, 0.035, 0.075}},
            {.id = kOceanGlintStrength,
             .name = "Sun Glint Strength",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.0,
             .range = {.minimum = 0.0, .maximum = 8.0}},
            {.id = kOceanMinimumDepthForDeepColorMeters,
             .name = "Deep Color Depth",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 40.0,
             .range = {.minimum = 0.001},
             .advanced = true}
        }
    });
    schemas.RegisterType({
        .id = kCloudLayerCapabilityType,
        .displayName = "Cloud Layer",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Volumetric Layer"),
            SourceObjectProperty(),
            {.id = kCloudSourceModel,
             .name = "Source Model",
             .kind = schema::PropertyKind::String,
             .defaultValue = std::string{"Climate Procedural"}},
            {.id = kCloudBaseAltitudeMeters,
             .name = "Base Altitude",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1500.0,
             .range = {.minimum = 0.0}},
            {.id = kCloudTopAltitudeMeters,
             .name = "Top Altitude",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 6500.0,
             .range = {.minimum = 0.0}},
            {.id = kCloudCoverageBias,
             .name = "Coverage Bias",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.0,
             .range = {.minimum = -1.0, .maximum = 1.0}},
            {.id = kCloudOpticalDepth,
             .name = "Peak Optical Depth",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 8.0,
             .range = {.minimum = 0.0}},
            {.id = kCloudSingleScatteringAlbedo,
             .name = "Single Scattering Albedo",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.999,
             .range = {.minimum = 0.0, .maximum = 1.0},
             .advanced = true},
            {.id = kCloudAnisotropy,
             .name = "Phase Anisotropy",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.72,
             .range = {.minimum = -0.999, .maximum = 0.999},
             .advanced = true},
            {.id = kCloudDensityExponent,
             .name = "Density Exponent",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.35,
             .range = {.minimum = 0.05},
             .advanced = true},
            {.id = kCloudWeatherScale,
             .name = "Weather Scale",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 3.5,
             .range = {.minimum = 0.01},
             .advanced = true},
            {.id = kCloudDetailScale,
             .name = "Detail Scale",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 14.0,
             .range = {.minimum = 0.01},
             .advanced = true},
            {.id = kCloudSeed,
             .name = "Seed",
             .kind = schema::PropertyKind::Integer,
             .defaultValue = i64{1},
             .advanced = true},
            {.id = kCloudWindAngularRadiansPerSecond,
             .name = "Wind Angular Velocity",
             .kind = schema::PropertyKind::Vector3,
             .unit = "rad/s",
             .defaultValue = math::Double3{0.0, 0.0, 7.272205e-6},
             .advanced = true},
            {.id = kCloudPrecipitationPhase,
             .name = "Precipitation Phase",
             .kind = schema::PropertyKind::String,
             .defaultValue = std::string{"Mixed"},
             .advanced = true},
            {.id = kCloudShadowParticipation,
             .name = "Cast Cloud Shadows",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true},
            {.id = kCloudOrbitalRepresentation,
             .name = "Visible From Orbit",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true}
        }
    });
    schemas.RegisterType({
        .id = kRingSystemCapabilityType,
        .displayName = "Ring System",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Particle Distribution"),
            {.id = kRingPlaneNormalBody,
             .name = "Ring Plane Normal",
             .kind = schema::PropertyKind::Vector3,
             .defaultValue = math::Double3{0.0, 1.0, 0.0}},
            {.id = kRingShadowParticipation,
             .name = "Cast Ring Shadows",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true},
            {.id = kRingBodyShadowEnabled,
             .name = "Receive Body Shadow",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true}
        }
    });
    schemas.RegisterType({
        .id = kRingBandType,
        .displayName = "Ring Band",
        .category = "Celestial/Ring",
        .properties = {
            EnabledProperty(),
            ModelProperty("Physical Band"),
            {.id = kRingBandInnerRadiusMeters,
             .name = "Inner Radius",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 8.0e7,
             .range = {.minimum = 0.0}},
            {.id = kRingBandOuterRadiusMeters,
             .name = "Outer Radius",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 1.4e8,
             .range = {.minimum = 0.000001}},
            {.id = kRingBandOpticalDepth,
             .name = "Normal Optical Depth",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.7,
             .range = {.minimum = 0.0}},
            {.id = kRingBandSingleScatteringAlbedo,
             .name = "Single Scattering Albedo",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.65,
             .range = {.minimum = 0.0, .maximum = 1.0}},
            {.id = kRingBandAnisotropy,
             .name = "Phase Anisotropy",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 0.35,
             .range = {.minimum = -0.999, .maximum = 0.999},
             .advanced = true},
            {.id = kRingBandColorLinear,
             .name = "Ring Color",
             .kind = schema::PropertyKind::Vector3,
             .defaultValue = math::Double3{0.72, 0.66, 0.56}},
            {.id = kRingBandThicknessMeters,
             .name = "Physical Thickness",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 100.0,
             .range = {.minimum = 0.0},
             .advanced = true}
        }
    });
    schemas.RegisterType({
        .id = kRadiativeEmitterCapabilityType,
        .displayName = "Radiative Emitter",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Blackbody"),
            {.id = kEmitterLuminosityWatts,
             .name = "Bolometric Luminosity",
             .kind = schema::PropertyKind::Float,
             .unit = "W",
             .defaultValue = 3.828e26,
             .range = {.minimum = 0.0}},
            {.id = kEmitterEffectiveTemperatureKelvin,
             .name = "Effective Temperature",
             .kind = schema::PropertyKind::Float,
             .unit = "K",
             .defaultValue = 5772.0,
             .range = {.minimum = 0.000001}},
            {.id = kEmitterEmissivity,
             .name = "Emissivity",
             .kind = schema::PropertyKind::Float,
             .defaultValue = 1.0,
             .range = {.minimum = 0.0, .maximum = 1.0}},
            {.id = kEmitterDeriveLuminosity,
             .name = "Derive Luminosity From Photosphere",
             .kind = schema::PropertyKind::Boolean,
             .defaultValue = true}
        }
    });

    schemas.RegisterType({
        .id = kPhotosphereCapabilityType,
        .displayName = "Photosphere",
        .category = "Celestial/Capability",
        .properties = {
            EnabledProperty(),
            ModelProperty("Blackbody"),
            {.id = kPhotosphereRadiusMeters,
             .name = "Photosphere Radius",
             .kind = schema::PropertyKind::Float,
             .unit = "m",
             .defaultValue = 6.957e8,
             .range = {.minimum = 0.000001}},
            {.id = kPhotosphereTemperatureKelvin,
             .name = "Effective Temperature",
             .kind = schema::PropertyKind::Float,
             .unit = "K",
             .defaultValue = 5772.0,
             .range = {.minimum = 0.000001}}
        }
    });
    RegisterCapability(
        schemas, kMagnetosphereCapabilityType,
        "Magnetosphere / Aurora", "Parameterized");
    RegisterCapability(
        schemas, kCometTailCapabilityType,
        "Comet Tail", "Solar Driven");
    RegisterCapability(
        schemas, kCompactObjectCapabilityType,
        "Compact Object", "Disabled");
    RegisterCapability(
        schemas, kAccretionFlowCapabilityType,
        "Accretion Flow", "Disabled");
}
} // namespace orbit::world_model
