from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'anchor not found in {path}')
    file.write_text(text.replace(old, new, 1), encoding='utf-8')


replace_once(
    'engine/editor_ui/include/orbit/editor_ui/EditorUi.hpp',
    '''    void Toolbar(std::span<const ActionPresentation> actions);\n    void ContextMenu(std::string_view id, std::span<const ActionPresentation> actions, bool openRequested);\n''',
    '''    void Toolbar(std::span<const ActionPresentation> actions);\n    // Generic popup surface for rich transient UI such as command palettes.\n    // Call EndPopup only when BeginPopup returns true. A zero size axis is\n    // auto-fit by ImGui; non-zero dimensions apply when the popup appears.\n    [[nodiscard]] bool BeginPopup(\n        std::string_view id,\n        bool openRequested,\n        UiSize size = {});\n    void EndPopup();\n    void CloseCurrentPopup();\n    void ContextMenu(std::string_view id, std::span<const ActionPresentation> actions, bool openRequested);\n''')

replace_once(
    'engine/editor_ui/src/EditorUi.cpp',
    '''void PanelContext::ContextMenu(\n    const std::string_view id,\n    const std::span<const ActionPresentation> actions,\n    const bool openRequested)\n{\n''',
    '''bool PanelContext::BeginPopup(\n    const std::string_view id,\n    const bool openRequested,\n    const UiSize size)\n{\n    const std::string ownedId(id);\n\n    if (openRequested)\n    {\n        ImGui::OpenPopup(ownedId.c_str());\n    }\n\n    if (size.width > 0.0F || size.height > 0.0F)\n    {\n        ImGui::SetNextWindowSize(\n            ImVec2(\n                std::max(size.width, 0.0F),\n                std::max(size.height, 0.0F)),\n            ImGuiCond_Appearing);\n    }\n\n    return ImGui::BeginPopup(ownedId.c_str());\n}\n\nvoid PanelContext::EndPopup()\n{\n    ImGui::EndPopup();\n}\n\nvoid PanelContext::CloseCurrentPopup()\n{\n    ImGui::CloseCurrentPopup();\n}\n\nvoid PanelContext::ContextMenu(\n    const std::string_view id,\n    const std::span<const ActionPresentation> actions,\n    const bool openRequested)\n{\n''')

replace_once(
    'engine/studio_ui/include/orbit/studio_ui/StudioExpansionShell.hpp',
    '''    std::string commandQuery_;\n    bool commandSearchOpen_{false};\n    bool quickCreateOpen_{false};\n''',
    '''    std::string commandQuery_;\n    bool quickCreateOpen_{false};\n''')

replace_once(
    'engine/studio_ui/src/StudioExpansionShell.cpp',
    '''    context.SameLine();\n    if (context.Button(\n            commandSearchOpen_\n                ? "Close Commands##command-palette-toggle"\n                : "Commands##command-palette-toggle"))\n    {\n        commandSearchOpen_ = !commandSearchOpen_;\n        if (!commandSearchOpen_)\n        {\n            commandQuery_.clear();\n        }\n    }\n\n    auto& registry = world.CommandRegistry();\n    const auto palette =\n        BuildCommandPalette(registry.Catalog());\n\n    if (commandSearchOpen_)\n    {\n        context.SameLine();\n        static_cast<void>(\n            context.InputText(\n                "##studio-command-palette-query",\n                commandQuery_));\n\n        const auto matches =\n            SearchCommandPalette(\n                palette,\n                commandQuery_,\n                8U);\n\n        std::size_t shown = 0U;\n        for (const auto& entry : matches)\n        {\n            if (entry.requiresArguments)\n            {\n                continue;\n            }\n\n            const auto enablement =\n                registry.Enablement(entry.command);\n            if (!enablement.enabled)\n            {\n                continue;\n            }\n\n            context.SameLine();\n            std::string label = entry.label;\n            label += "##palette-";\n            label += entry.command.ToString();\n            if (context.Button(label))\n            {\n                try\n                {\n                    registry.Invoke(entry.command);\n                    owner_->status_.clear();\n                    commandSearchOpen_ = false;\n                    commandQuery_.clear();\n                }\n                catch (const std::exception& exception)\n                {\n                    owner_->status_ = exception.what();\n                }\n            }\n\n            if (++shown >= 2U)\n            {\n                break;\n            }\n        }\n    }\n''',
    '''    context.SameLine();\n    const bool openCommandPalette =\n        context.Button("Commands##command-palette-toggle");\n    if (openCommandPalette)\n    {\n        commandQuery_.clear();\n    }\n\n    auto& registry = world.CommandRegistry();\n    const auto palette =\n        BuildCommandPalette(registry.Catalog());\n\n    const f32 commandPaletteWidth =\n        520.0F * editor_ui::CurrentUiScale();\n    if (context.BeginPopup(\n            "studio-command-palette-popup",\n            openCommandPalette,\n            {.width = commandPaletteWidth, .height = 0.0F}))\n    {\n        context.Text("Commands");\n        static_cast<void>(\n            context.InputText(\n                "##studio-command-palette-query",\n                commandQuery_));\n        context.Separator();\n\n        const auto matches =\n            SearchCommandPalette(\n                palette,\n                commandQuery_,\n                16U);\n\n        std::size_t shown = 0U;\n        for (const auto& entry : matches)\n        {\n            if (entry.requiresArguments)\n            {\n                continue;\n            }\n\n            const auto enablement =\n                registry.Enablement(entry.command);\n            if (!enablement.enabled)\n            {\n                continue;\n            }\n\n            std::string label = entry.label;\n            label += "##palette-";\n            label += entry.command.ToString();\n            if (context.Selectable(label, false))\n            {\n                try\n                {\n                    registry.Invoke(entry.command);\n                    owner_->status_.clear();\n                    commandQuery_.clear();\n                    context.CloseCurrentPopup();\n                }\n                catch (const std::exception& exception)\n                {\n                    owner_->status_ = exception.what();\n                }\n            }\n\n            if (++shown >= 8U)\n            {\n                break;\n            }\n        }\n\n        if (shown == 0U)\n        {\n            context.MutedText("No matching enabled commands.");\n        }\n\n        context.EndPopup();\n    }\n''')
